using System.Text;
using System.Text.RegularExpressions;
using CGen;
using RecompOne.Recompiler.Analysis;
using RecompOne.Recompiler.CodeGen;
using RecompOne.Recompiler.Config;
using RecompOne.Recompiler.Disasm;
using RecompOne.Recompiler.Symbols;
using RecompOne.Recompiler.Psx;
using RecompOne.Runtime.Cdrom;

// cgen <config.json> <outDir> [--comments]
// Runs RecompOne's analysis and writes C sources for the 3DS runtime.
if (args.Length < 2)
{
    Console.Error.WriteLine("usage: cgen <config.json> <outDir> [--comments]");
    return 1;
}

string configPath = Path.GetFullPath(args[0]);
string outDir = Path.GetFullPath(args[1]);
bool comments = args.Contains("--comments");

var config = ConfigLoader.Load(configPath);
string configDir = Path.GetDirectoryName(configPath)!;
string? Resolve(string? p) => p == null ? null : Path.IsPathRooted(p) ? p : Path.GetFullPath(Path.Combine(configDir, p));
config.Elf = Resolve(config.Elf);
config.Map = Resolve(config.Map);
config.FuncMap = Resolve(config.FuncMap);
foreach (var o in config.Overlays)
{
    o.Elf = Resolve(o.Elf);
    o.Map = Resolve(o.Map);
    o.FuncMap = Resolve(o.FuncMap);
}

string cuePath = Path.GetFullPath(Path.Combine(configDir, config.Cue));
if (!File.Exists(cuePath))
{
    Console.Error.WriteLine($"disc file not found: {cuePath}");
    return 1;
}

Directory.CreateDirectory(outDir);
foreach (var f in Directory.GetFiles(outDir, "*.c")) File.Delete(f);

var fs = DiscFs.Open(cuePath);
var sysCfg = SystemCfg.Parse(fs);
var mainExe = Parser.ParseExe(fs, sysCfg.BootExe);
Console.WriteLine($"[cgen] BOOT={sysCfg.BootExe} PC=0x{mainExe.InitialPC:X8} GP=0x{mainExe.InitialGP:X8} SP=0x{mainExe.InitialSP:X8} load=0x{mainExe.Destination:X8}");

var results = new List<Analysis.Overlay>();
results.Add(Analysis.AnalyzeMain(config, mainExe));
foreach (var oc in config.Overlays)
{
    var a = OverlayWriter.AnalyzeOverlay(config, oc, fs);
    if (a == null) continue;
    results.Add(new Analysis.Overlay(oc.Name, a.Functions, a.Lba, a.Base, (uint)a.DiscBin.Length, a.Instructions)
        { SigLen = (uint)Math.Min(256, a.DiscBin.Length & ~3), Sig = Analysis.Fnv(a.DiscBin, Math.Min(256, a.DiscBin.Length & ~3)) });
}

var allFuncs = results.SelectMany(o => o.Functions).ToList();
Analysis.ResolveCollisions(allFuncs);

// config patches: only targets that have a C implementation are honoured
var cHooks = new Dictionary<string, string>(StringComparer.Ordinal)
{
    ["Recompiled.FunctionFixes.ScyllaDoorFix"] = "fix_scylla_door",
    ["Recompiled.FunctionFixes.OlroxExploFix"] = "fix_olrox_explosion",
    ["Recompiled.FunctionFixes.ClockCollisionFix"] = "fix_clock_collision",
    ["Recompiled.FunctionFixes.MinotaurAndWerewolfFix"] = "fix_minotaur_werewolf",
};
var pre = new Dictionary<MipsFunction, List<string>>();
var post = new Dictionary<MipsFunction, List<string>>();
var cpatch = new Dictionary<MipsFunction, string>();
Analysis.ApplyPatches(allFuncs, config.Patches, cHooks, pre, post);

SdkPatches.Apply(allFuncs);
foreach (var f in allFuncs)
    if (f.IsPatch && f.PatchTarget.StartsWith("RecompOne.Runtime.Sdk.", StringComparison.Ordinal))
        cpatch[f] = "sdk_" + f.PatchTarget["RecompOne.Runtime.Sdk.".Length..].Replace('.', '_');

var uniqueAddrs = allFuncs.GroupBy(f => f.Start).Where(g => g.Count() == 1).Select(g => g.Key).ToHashSet();
string CName(MipsFunction f) => "f_" + f.EmittedName;
var known = allFuncs.Where(f => uniqueAddrs.Contains(f.Start)).ToDictionary(f => f.Start, CName);
Console.WriteLine($"[cgen] total functions: {allFuncs.Count}, statically linked: {known.Count}");

string? mainCall = null;
if (config.Main != null)
{
    uint mainAddr = Convert.ToUInt32(config.Main, 16);
    var mf = allFuncs.First(f => f.Start == mainAddr);
    mainCall = CName(mf);
}

const int ChunkChars = 6_000_000;
var sources = new List<string>();
long totalChars = 0;

foreach (var ovl in results)
{
    int part = 0;
    var body = new StringBuilder();
    var defined = new List<string>();
    var callees = new HashSet<string>();

    void Flush()
    {
        if (body.Length == 0) return;
        var file = new StringBuilder();
        file.AppendLine("/* generated by port3ds/cgen - do not edit */");
        file.AppendLine("#include \"recomp.h\"");
        file.AppendLine();
        var decl = new SortedSet<string>(callees, StringComparer.Ordinal);
        foreach (var d in defined) decl.Add(d);
        foreach (var d in decl) file.AppendLine($"void {d}(Cpu *restrict c);");
        file.AppendLine();
        file.Append(body);
        string fname = $"ovl_{ovl.Name}_{part}.c";
        File.WriteAllText(Path.Combine(outDir, fname), file.ToString());
        sources.Add(fname);
        totalChars += file.Length;
        part++;
        body.Clear();
        defined.Clear();
        callees.Clear();
    }

    foreach (var func in ovl.Functions.OrderBy(f => f.Start))
    {
        var ctx = new CFuncContext
        {
            FuncStart = func.Start,
            FuncEnd = func.End,
            KnownFunctions = known,
            Labels = LabelManager.Collect(func),
            JumpTablesByJr = func.JumpTables.GroupBy(j => j.JrVram).ToDictionary(g => g.Key, g => g.First()),
            RaReturnJrs = FunctionDetector.ComputeRaReturnJrs(func),
            AllInstructions = ovl.Instructions,
            Comments = comments,
        };
        string cname = CName(func);
        cpatch.TryGetValue(func, out var pt);
        if (pt != null) callees.Add(pt);
        body.Append(CEmitter.EmitFunction(func, ctx, cname, pt,
            pre.GetValueOrDefault(func) ?? [], post.GetValueOrDefault(func) ?? []));
        body.AppendLine();
        defined.Add(cname);
        foreach (var cl in ctx.Callees) callees.Add(cl);
        if (body.Length > ChunkChars) Flush();
    }
    Flush();
}

// sdk / hook prototypes are declared in recomp.h; make sure every sdk target exists in a header list
var sdkNames = cpatch.Values.Distinct().OrderBy(s => s).ToList();

// overlay tables
{
    var sb = new StringBuilder();
    sb.AppendLine("/* generated by port3ds/cgen - do not edit */");
    sb.AppendLine("#include \"recomp.h\"");
    sb.AppendLine();
    var all = new SortedSet<string>(StringComparer.Ordinal);
    foreach (var ovl in results)
        foreach (var f in ovl.Functions.Where(f => !f.IsStub)) all.Add(CName(f));
    foreach (var n in all) sb.AppendLine($"void {n}(Cpu *restrict c);");
    sb.AppendLine();
    foreach (var ovl in results)
    {
        var funcs = ovl.Functions.Where(f => !f.IsStub).OrderBy(f => f.Start).ToList();
        sb.AppendLine($"static const FuncEntry ovl_{ovl.Name}_funcs[] = {{");
        foreach (var f in funcs) sb.AppendLine($"    {{ 0x{f.Start:X8}u, {CName(f)} }},");
        if (funcs.Count == 0) sb.AppendLine("    { 0, 0 },");
        sb.AppendLine("};");
    }
    sb.AppendLine();
    sb.AppendLine("const OverlayDesc g_overlays[] = {");
    foreach (var ovl in results)
    {
        int n = ovl.Functions.Count(f => !f.IsStub);
        sb.AppendLine($"    {{ \"{ovl.Name}\", {ovl.LbaStart}, 0x{ovl.Base:X8}u, 0x{ovl.Size:X}u, ovl_{ovl.Name}_funcs, {n}, 0x{ovl.Sig:X8}u, {ovl.SigLen} }},");
    }
    sb.AppendLine("};");
    sb.AppendLine($"const int g_overlay_count = {results.Count};");
    sb.AppendLine();
    sb.AppendLine($"const char g_boot_exe[] = \"{sysCfg.BootExe.Replace("\\", "\\\\")}\";");
    sb.AppendLine($"const u32 g_boot_dest = 0x{mainExe.Destination:X8}u;");
    sb.AppendLine($"const u32 g_boot_text_size = 0x{mainExe.TextSize:X}u;");
    sb.AppendLine($"const u32 g_boot_pc = 0x{mainExe.InitialPC:X8}u;");
    sb.AppendLine($"const u32 g_boot_gp = 0x{mainExe.InitialGP:X8}u;");
    sb.AppendLine($"const u32 g_boot_sp = 0x{mainExe.InitialSP:X8}u;");
    sb.AppendLine($"const FuncPtr g_boot_main = {(mainCall ?? "0")};");
    File.WriteAllText(Path.Combine(outDir, "overlays.c"), sb.ToString());
    sources.Add("overlays.c");
}

File.WriteAllText(Path.Combine(outDir, "sdk_used.txt"), string.Join("\n", sdkNames));
File.WriteAllText(Path.Combine(outDir, "sources.mk"), "GEN_SOURCES := " + string.Join(" ", sources) + "\n");
Console.WriteLine($"[cgen] wrote {sources.Count} files, {totalChars / (1024 * 1024)} MB of C, unknown ops: {CEmitter.UnknownCount}");
return 0;

static class Analysis
{
    public sealed record Overlay(string Name, List<MipsFunction> Functions, int LbaStart, uint Base, uint Size, MipsInstruction[] Instructions)
    {
        public uint Sig { get; init; }
        public uint SigLen { get; init; }
    }

    // FNV-1a, matched by sig_hash() in dispatch.c
    public static uint Fnv(byte[] d, int n)
    {
        uint h = 2166136261u;
        for (int i = 0; i < n; i++) { h ^= d[i]; h *= 16777619u; }
        return h;
    }

    // same steps as OverlayWriter.Write for the main executable
    public static Overlay AnalyzeMain(RecompOneConfig config, PsxExe mainExe)
    {
        List<MipsFunction> funcs;
        MipsInstruction[] mainInstrs;
        FunctionInfo? elfInfo = null;

        FunctionInfo? rawElf = config.Elf != null ? RecompOne.Recompiler.Elf.ElfReader.Read(config.Elf) : null;
        FunctionInfo? rawMap = config.Map != null ? RecompOne.Recompiler.Map.MapReader.Read(config.Map) : null;
        FunctionInfo? rawFuncMap = null;
        if (config.FuncMap != null && !config.LinearSweep)
        {
            uint funcMapBase = rawElf?.TextBase ?? rawMap?.LoadAddress ?? mainExe.Destination;
            rawFuncMap = FunctionMapLoader.Load(config.FuncMap, funcMapBase, mainExe.Code);
        }

        if (rawElf != null || rawMap != null || rawFuncMap != null)
        {
            elfInfo = FunctionMapLoader.Merge(rawElf, rawMap, rawFuncMap);
            if (elfInfo.TextData.Length == 0) elfInfo.TextData = mainExe.Code;
            mainInstrs = MipsDisasm.Disassemble(mainExe.Code, elfInfo.TextBase);
            funcs = elfInfo.Functions.Count > 0 ? FunctionDetector.DetectFromElf(mainInstrs, elfInfo, "main") : FunctionDetector.DetectFromScan(mainInstrs, elfInfo.LoadAddress, "main");
        }
        else
        {
            mainInstrs = MipsDisasm.Disassemble(mainExe.Code, mainExe.Destination);
            funcs = FunctionDetector.DetectFromScan(mainInstrs, mainExe.InitialPC, "main");
            elfInfo = new FunctionInfo { TextBase = mainExe.Destination, LoadAddress = mainExe.Destination, TextData = mainExe.Code };
        }

        if (funcs.All(f => f.Start != mainExe.InitialPC))
            funcs.AddRange(FunctionDetector.DetectFromAddresses(mainInstrs, [(mainExe.InitialPC, null)], funcs, "main"));

        funcs.AddRange(FunctionDetector.DiscoverCalls(mainInstrs, funcs, elfInfo.NoTypeSymbols, "main"));
        AddConfigFunctions(funcs, config.Functions, mainInstrs, elfInfo.NoTypeSymbols, "main");
        if (config.LinearSweep)
        {
            var swept = FunctionDetector.LinearSweep(mainInstrs, funcs, elfInfo.NoTypeSymbols, "main");
            funcs.AddRange(swept);
            funcs.AddRange(FunctionDetector.DiscoverCalls(mainInstrs, funcs, elfInfo.NoTypeSymbols, "main"));
        }
        foreach (var f in funcs) f.JumpTables = JumpTableAnalyzer.Analyze(f, elfInfo);
        ApplyStubsAndIgnored(funcs, config.Stubs, config.Ignored);
        return new Overlay("main", funcs, -1, 0, 0, mainInstrs);
    }

    static void AddConfigFunctions(List<MipsFunction> funcs, RecompOne.Recompiler.Config.FunctionEntry[] entries, MipsInstruction[] instrs, IEnumerable<RecompOne.Recompiler.Symbols.FunctionEntry> noType, string ovl)
    {
        if (entries.Length == 0) return;
        var byStart = funcs.GroupBy(f => f.Start).ToDictionary(g => g.Key, g => g.First());
        var missing = new List<(uint, string?)>();
        foreach (var e in entries)
        {
            uint addr = Convert.ToUInt32(e.Address, 16);
            if (!byStart.TryGetValue(addr, out var ex)) { missing.Add((addr, e.Name)); continue; }
            if (!string.IsNullOrEmpty(e.Name)) ex.Name = e.Name;
        }
        if (missing.Count == 0) return;
        funcs.AddRange(FunctionDetector.DetectFromAddresses(instrs, missing, funcs, ovl));
        funcs.AddRange(FunctionDetector.DiscoverCalls(instrs, funcs, noType, ovl));
    }

    static void ApplyStubsAndIgnored(List<MipsFunction> funcs, IEnumerable<string> stubs, IEnumerable<string> ignored)
    {
        var stubSet = new HashSet<string>(stubs, StringComparer.OrdinalIgnoreCase);
        var ignoredSet = new HashSet<string>(ignored, StringComparer.OrdinalIgnoreCase);
        foreach (var f in funcs)
        {
            if (ignoredSet.Contains(f.Name)) { f.IsStub = true; f.Name = "__ignored__"; }
            else if (stubSet.Contains(f.Name)) f.IsStub = true;
        }
        funcs.RemoveAll(f => f.Name == "__ignored__");
    }

    static string SafeIdentifier(string s) => Regex.Replace(s, @"[^a-zA-Z0-9_]", "_").TrimStart('0', '1', '2', '3', '4', '5', '6', '7', '8', '9');
    static string SafeFuncName(string s) => Regex.Replace(s, @"[^A-Za-z0-9_]", "_");

    public static void ResolveCollisions(List<MipsFunction> allFuncs)
    {
        var crossOverlayDups = allFuncs.GroupBy(f => f.Name)
            .Where(g => g.Select(f => f.OverlayName).Distinct().Count() > 1)
            .Select(g => g.Key).ToHashSet();
        foreach (var func in allFuncs)
            func.EmittedName = SafeFuncName(crossOverlayDups.Contains(func.Name) && !string.IsNullOrEmpty(func.OverlayName)
                ? $"{func.Name}_{SafeIdentifier(func.OverlayName)}"
                : func.Name);
        foreach (var group in allFuncs.GroupBy(f => (f.OverlayName, f.EmittedName)).Where(g => g.Count() > 1))
            foreach (var func in group)
                func.EmittedName = $"{func.EmittedName}_{func.Start:X8}";
        // C has a single namespace: make the final names globally unique as well
        foreach (var group in allFuncs.GroupBy(f => f.EmittedName).Where(g => g.Count() > 1))
            foreach (var func in group)
                func.EmittedName = $"{func.EmittedName}_{SafeIdentifier(func.OverlayName)}_{func.Start:X8}";
    }

    static bool PatchNameMatches(MipsFunction func, string? patchFunction)
    {
        if (string.IsNullOrEmpty(patchFunction)) return false;
        if (string.Equals(func.Name, patchFunction, StringComparison.Ordinal)) return true;
        if (string.IsNullOrEmpty(func.OverlayName)) return false;
        return string.Equals(func.Name, $"{func.OverlayName.ToUpperInvariant()}_{patchFunction}", StringComparison.Ordinal);
    }

    public static void ApplyPatches(List<MipsFunction> funcs, PatchEntry[] patches, Dictionary<string, string> cHooks,
        Dictionary<MipsFunction, List<string>> pre, Dictionary<MipsFunction, List<string>> post)
    {
        int applied = 0, skipped = 0;
        foreach (var patch in patches)
        {
            if (!cHooks.TryGetValue(patch.Target, out var target)) { skipped++; continue; }
            uint? addr = string.IsNullOrEmpty(patch.Address) ? null : Convert.ToUInt32(patch.Address, 16);
            foreach (var func in funcs)
            {
                if (!patch.MatchesOverlay(func.OverlayName)) continue;
                bool hit = addr.HasValue ? func.Start == addr.Value : PatchNameMatches(func, patch.Function);
                if (!hit) continue;
                var dict = patch.Mode.Equals("post", StringComparison.OrdinalIgnoreCase) ? post : pre;
                if (!dict.TryGetValue(func, out var list)) dict[func] = list = [];
                if (!list.Contains(target)) list.Add(target);
                applied++;
            }
        }
        Console.WriteLine($"[cgen] applied {applied} C hooks, skipped {skipped} PC-only patches");
    }
}
